Repository Arquisoft/wiq_en1a, pull requests merged in 2024-03, with the labels that each got.

#38 Readme Update & quickfix of deployment
  .github/workflows/release.yml
  README.md
Labels: Bug 🐛

#40 Backend for rankings
  gatewayservice/package-lock.json
  gatewayservice/package.json
  users/authservice/auth-service.js
  users/authservice/package-lock.json
  users/authservice/package.json
  users/userservice/user-model.js
  users/userservice/user-service.js
Labels: Enhancement ✴️

#41 Rankings
  gatewayservice/gateway-service.js
  questionservice/package-lock.json
  questionservice/package.json
  users/userservice/user-service.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Rankings.jsx
  webapp/src/index.css
  webapp/tailwind.config.js
Labels: Enhancement ✴️

#42 Added navbar
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/Navbar.jsx
Labels: Enhancement ✴️

#48 Login Local Storage and backend
  gatewayservice/gateway-service.js
  users/authservice/auth-service.js
  users/userservice/user-service.js
  webapp/src/App.js
  webapp/src/components/Login.js
  webapp/src/index.js
Labels: Enhancement ✴️

#51 Game and styling
  questionservice/question-service.js
  webapp/src/App.jsx
  webapp/src/components/Game.jsx
  webapp/src/components/Login.js
  webapp/src/components/Navbar.jsx
  webapp/src/components/Question.jsx
  webapp/src/components/Rankings.jsx
Labels: Enhancement ✴️

#55 Fixed answered flag bug
  gatewayservice/gateway-service.js
  questionservice/question-service.js
  webapp/src/components/Question.jsx
Labels: Bug 🐛

#60 Fixed navbar
  webapp/src/components/Navbar.jsx
Labels: Enhancement ✴️

#63 Authentication + Docker
  .github/workflows/release.yml
  docker-compose.yml
  questionservice/.dockerignore
  questionservice/Dockerfile
  users/authservice/auth-model.js
  users/authservice/auth-service.js
  users/userservice/user-model.js
  users/userservice/user-service.js
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.jsx
  webapp/src/components/AddUser.js
  webapp/src/components/Game.jsx
  webapp/src/components/Login.js
  webapp/src/components/MainPage.jsx
  webapp/src/components/Navbar.jsx
  webapp/src/index.js
Labels: Enhancement ✴️

#71 Hotfix deploy
  .github/workflows/release.yml
  webapp/src/components/Question.jsx
  webapp/src/components/Rankings.jsx
Labels: Bug 🐛, Deployment 🚀

#73 Merge hotfixes
  .github/workflows/release.yml
  docker-compose.yml
  webapp/src/components/Question.jsx
  webapp/src/components/Rankings.jsx
Labels: Bug 🐛, Urgent ⚠️

#78 Hotfix v0.1.2
  users/authservice/auth-service.js
  users/userservice/user-service.js
  webapp/public/index.html
  webapp/public/manifest.json
  webapp/src/App.jsx
  webapp/src/components/AddUser.jsx
  webapp/src/components/Game.jsx
  webapp/src/components/Login.jsx
Labels: Bug 🐛

#81 Open api+pre v0.2.0
  README.md
  gatewayservice/gateway-service.js
  gatewayservice/openapi.yaml
  gatewayservice/package-lock.json
  gatewayservice/package.json
  questionservice/question-service.js
  users/authservice/auth-service.js
  users/userservice/user-service.js
  webapp/src/components/Game.jsx
Labels: Bug 🐛, Documentation 📖, Back End 🔌
