Repository Arquisoft/wiq_en1a, pull requests merged in 2024-04, with the labels that each got.

#82 fixed questions image bug
  questionservice/question-service.js
  webapp/src/components/Question.jsx
Labels: Bug 🐛

#83 Fix rankings example
  gatewayservice/openapi.yaml
Labels: Bug 🐛, Documentation 📖

#85 set time to questions, uncomment tests and new animation
  .github/workflows/release.yml
  webapp/src/components/AddUser.jsx
  webapp/src/components/Question.jsx
  webapp/src/index.js
Labels: Enhancement ✴️

#88 New Ranking
  gatewayservice/gateway-service.js
  users/userservice/package-lock.json
  users/userservice/package.json
  users/userservice/user-model.js
  users/userservice/user-service.js
  webapp/src/App.jsx
  webapp/src/components/Rankings.jsx
  webapp/src/components/ranking/RankingLayout.jsx
  webapp/src/components/ranking/RankingTable.jsx
Labels: Enhancement ✴️

#97 User service and Authentication in frontend testing + question service hotfixes
  questionservice/package-lock.json
  questionservice/question-service.js
  users/userservice/user-service.test.js
  webapp/src/App.test.js
  webapp/src/components/AddUser.jsx
  webapp/src/components/AddUser.test.js
  webapp/src/components/Login.jsx
  webapp/src/components/Login.test.js
  webapp/src/components/MainPage.jsx
  webapp/src/components/MainPage.test.js
Labels: Bug 🐛, Testing ✅️, Front End 📱, Back End 🔌

#100 Rankings
  users/userservice/package-lock.json
  users/userservice/package.json
  users/userservice/user-service.js
  webapp/src/components/ranking/RankingLayout.jsx
Labels: Bug 🐛, Enhancement ✴️

#105 Test-rankings
  questionservice/question-service.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/src/components/Game.test.js
Labels: Enhancement ✴️

#106 deployment view
  docs/src/07_deployment_view.adoc
Labels: Documentation 📖

#108 added rankings test and removed duplicated code
  users/userservice/user-service.test.js
  webapp/src/components/ranking/Ranking.test.js
  webapp/src/components/ranking/RankingTable.jsx
Labels: Enhancement ✴️

#112 docu
  docs/src/04_solution_strategy.adoc
  docs/src/06_runtime_view.adoc
Labels: Documentation 📖

#137 user profile and some fancy css all around
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  users/userservice/user-service.js
  webapp/public/profile_img.webp
  webapp/src/App.jsx
  webapp/src/components/MainPage.jsx
  webapp/src/components/Squads.jsx
  webapp/src/components/UserProfile.jsx
  webapp/src/components/UserProfile.test.js
  webapp/src/components/auth/AddUser.jsx
  webapp/src/components/auth/AddUser.test.js
  webapp/src/components/auth/Login.jsx
  webapp/src/components/auth/Login.test.js
  webapp/src/components/game/Game.jsx
  webapp/src/components/game/Game.test.js
  webapp/src/components/game/ImgGameReport.jsx
  webapp/src/components/game/Question.jsx
  webapp/src/components/game/Question.test.js
  webapp/src/components/ranking/RankingLayout.jsx
  webapp/src/components/user/UserProfile.jsx
  webapp/src/components/user/UserProfile.test.js
  webapp/src/index.css
Labels: Enhancement ✴️, Front End 📱

#139 score more visible + fixed screen color when growing
  webapp/src/components/game/Game.jsx
  webapp/src/components/game/Question.jsx
  webapp/src/components/user/UserProfile.jsx
Labels: Bug 🐛, Enhancement ✴️, Front End 📱

#145 docs
  docs/src/09_architecture_decisions.adoc
  docs/src/11_technical_risks.adoc
  docs/src/12_glossary.adoc
Labels: Documentation 📖

#146 Tests Report and new relationships
  docs/index.adoc
  docs/src/03_system_scope_and_context.adoc
  docs/src/05_building_block_view.adoc
  docs/src/tests_report.adoc
Labels: Documentation 📖
